[package]
name = "lota"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cocoa = "0.25.0"
env_logger = "0.10"
log = "0.4"

[dependencies.ui]
path = "./ui"
